# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
selene = "Kampfkarren/selene@0.31.0"
stylua = "JohnnyMorganz/StyLua@2.5.2"
