local DailyRewardsConstants = {}

-------------------------------------------------------------------------------
-- PRIVATE VARIABLES
-------------------------------------------------------------------------------

local maxStreakDays = 7

-------------------------------------------------------------------------------
-- PUBLIC VARIABLES
-------------------------------------------------------------------------------

DailyRewardsConstants.MaxStreakDays = maxStreakDays

return DailyRewardsConstants
