local UIConstants = {}

-------------------------------------------------------------------------------
-- PUBLIC VARIABLES
-------------------------------------------------------------------------------

UIConstants.States = {
   HUD = "HUD",
   Store = "Store",
   SpawnPad = "SpawnPad",
   Armory = "Armory",
   Sell = "Sell",
   Index = "Index",
}

UIConstants.BaseState = UIConstants.States.HUD

return UIConstants
